// <auto-generated />
using EF_test_01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF_test_01.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220524083658_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF_test_01.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Abu Dabi",
                            Name = "Josh Gomez",
                            PhoneNumber = "123 456"
                        },
                        new
                        {
                            Id = 2,
                            City = "San Jose",
                            Name = "Miguel Alonso",
                            PhoneNumber = "234 567"
                        },
                        new
                        {
                            Id = 3,
                            City = "Stockholm",
                            Name = "Andreas Kvarnblom",
                            PhoneNumber = "345 678"
                        },
                        new
                        {
                            Id = 4,
                            City = "Stockholm",
                            Name = "Tore Kindwall",
                            PhoneNumber = "456 789"
                        },
                        new
                        {
                            Id = 5,
                            City = "Göteborg",
                            Name = "Helena Danielsson",
                            PhoneNumber = "567 890"
                        },
                        new
                        {
                            Id = 6,
                            City = "Alvesta",
                            Name = "Maria Persson",
                            PhoneNumber = "678 901"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
